name: Build and Deploy Backend to DockerHub

on:
  workflow_dispatch:
  # push:

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mern/server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Atlas URL
        working-directory: ./mern/server
        env:
          ATLAS_SERVER: ${{ secrets.ATLAS_SERVER }}
          ATLAS_USERNAME: ${{ secrets.ATLAS_USERNAME }}
          ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}
        run: echo "ATLAS_URI=mongodb+srv://${{ATLAS_USERNAME}}:${{ATLAS_PASSWORD}}@${{ATLAS_SERVER}}/" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: aidysproule/mern-app-1-backend:latest
