name: Build and Deploy Frontend to DockerHub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mern/client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./mern/client

      - name: Build Project
        run: npm run build
        working-directory: ./mern/client

      - name: Upload Aritfacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./mern/client/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Output contents
        run: ls

      - name: Get Dockerfile
        run: cp ./mern/client/Dockerfile-nginx-alpine .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile-nginx-alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: aidysproule/mern-app-1-frontend:latest
