name: Build and Deploy Frontend to DockerHub

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mern/client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./mern/client

      - name: Set Frontend URL
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env
        working-directory: ./mern/client

      - name: Confrim .env created
        run: ls -lash
        working-directory: ./mern/client

      - name: Show contents of .env file
        run: cat .env
        working-directory: ./mern/client

      - name: Build Project
        run: npm run build
        working-directory: ./mern/client

      - name: Upload Aritfacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./mern/client/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build-files

      - name: Get Dockerfile
        run: cp ./mern/client/Dockerfile-nginx-alpine ./build-files

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build-files/Dockerfile-nginx-alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: aidysproule/mern-app-1-frontend:latest
