name: Build and Deploy Frontend to DockerHub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ./mern/client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Uplaod Aritfacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    working-directory: ./mern/client
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Output contents
        run: ls
